"""Financial evidence supplements context, never current capital balances."""
import json
from datetime import date

import pytest

from ssm.models import Candidate, Dilution
from ssm.pipeline import build_candidate
from ssm.report import write_outputs

RECORD = {'form':'10-Q', 'filed':'2026-08-05', 'report_date':'2026-06-30',
          'accession':'financial', 'filename':'financial'}
ISSUE = 'On July 2, 2026, the Company issued 25 million shares of common stock in the Private Placement.'
REDEEM = ('On August 5, 2026, the Company redeemed all outstanding Series D Preferred Stock '
          'for an aggregate redemption price of $70 million (the “Redemption”).')
LINK = ('On August 5, 2026, the Company completed the Redemption utilizing cash received '
        'in the Private Placement.')
FINANCIAL = 'Note 18. Subsequent Events. '+ISSUE+' '+REDEEM+' '+LINK


def review(text, record=None, events=()):
    from ssm.financial_recapitalization import financial_capital_contexts
    return financial_capital_contexts(text, record or RECORD, events)


def test_explicit_named_financing_link_is_historical_read_only():
    rows=review(FINANCIAL)
    assert len(rows)==1
    cap=rows[0]['context']
    assert cap['assessment']=='RECAPITALIZATION_MIXED'
    assert cap['actual_common_issued']==25e6
    assert cap['financing_date']=='2026-07-02'
    assert cap['retirements'][0]['transaction_date']=='2026-08-05'
    assert cap['retirements'][0]['cash_paid']==70e6
    assert cap['retirements'][0]['whole_instrument'] is True
    assert cap['common_count_reconciliation']=='READ_ONLY_FINANCIAL_EVIDENCE'
    assert rows[0]['form']=='10-Q' and rows[0]['accession']=='financial'


def test_warrants_and_convertible_capacity_are_not_actual_common_issuance():
    for text in [
        'Note 9. Equity. In 2023, we issued warrants to purchase up to 2.0 million shares of our common stock.',
        'Note 9. Equity. On July 2, 2026, the Company issued Series D Preferred Stock convertible into 25 million shares of common stock.',
    ]:
        assert review(text)==[]


@pytest.mark.parametrize('retirement', [
    'On August 5, 2026, the Company used the proceeds to redeem all outstanding Series D Preferred Stock and acquired machinery for an aggregate payment of $70 million.',
    'On August 5, 2026, the Company used the proceeds to redeem Series D Preferred Stock for an aggregate redemption price of $70 million and redeemed a portion of Series E Preferred Stock.',
    'On August 5, 2026, the Company used the proceeds to redeem all outstanding Series D Preferred Stock for an aggregate redemption price of $70 million, using proceeds generated by its new senior notes.',
])
def test_unnamed_funding_other_purchase_and_other_series_cannot_confirm_link(retirement):
    rows=review('Note 18. Subsequent Events. '+ISSUE+' '+retirement)
    assert rows[0]['context']['link_verification']=='UNKNOWN'
    assert not rows[0]['context']['assessment'].startswith('RECAPITALIZATION_')


def test_named_link_cannot_supply_an_unrelated_asset_purchase_price():
    text=FINANCIAL.replace('redeemed all outstanding Series D Preferred Stock for an aggregate redemption price of $70 million',
                           'redeemed all outstanding Series D Preferred Stock and acquired machinery for an aggregate payment of $70 million')
    rows=review(text)
    assert rows[0]['context']['retirements'][0]['cash_paid'] is None
    assert rows[0]['context']['link_verification']=='UNKNOWN'


@pytest.mark.parametrize('text', [
    'Note 18. Subsequent Events. '+ISSUE+' '+REDEEM,
    FINANCIAL.replace('On August 5, 2026, the Company redeemed','The Company redeemed'),
    FINANCIAL.replace('all outstanding Series D Preferred Stock','Series D Preferred Stock'),
    FINANCIAL.replace('$70 million','an unspecified amount'),
    FINANCIAL.replace('Series D Preferred Stock','preferred stock'),
    FINANCIAL.replace('redeemed all','will redeem all'),
    FINANCIAL.replace('the Redemption utilizing','an unrelated redemption utilizing'),
])
def test_unproved_date_identity_amount_extent_or_link_remains_unknown(text):
    rows=review(text)
    assert rows
    assert all(not r['context']['assessment'].startswith('RECAPITALIZATION_') for r in rows)
    assert all(r['context']['reconciliation_required'] for r in rows)


def test_same_named_financing_at_different_dates_is_ambiguous():
    rows=review(FINANCIAL+' On July 15, 2026, the Company issued 25 million shares of common stock in the Private Placement.')
    assert all(not r['context']['assessment'].startswith('RECAPITALIZATION_') for r in rows)


def test_repeated_financial_note_and_mda_do_not_add_shares_or_cash_twice():
    rows=review(FINANCIAL+' Item 2. Liquidity. '+ISSUE+' '+REDEEM+' '+LINK)
    assert len(rows)==1
    assert rows[0]['context']['actual_common_issued']==25e6
    assert rows[0]['context']['retirements'][0]['cash_paid']==70e6


def test_8k_duplicate_keeps_one_record_and_both_source_links():
    from ssm.recapitalization import capital_context
    narrative=('On July 2, 2026, the Company issued 25 million shares of common stock. '
               'On August 5, 2026, the Company used the proceeds to redeem $70 million of Series D Preferred Stock. '
               'On August 5, 2026, all outstanding Series D Preferred Stock was extinguished.')
    event={'accession':'8k', 'filed':'2026-08-05', 'sources':['https://www.sec.gov/8k'],
           'combined_text':narrative, 'terms':{'capital_context':capital_context(narrative)}}
    rows=review(FINANCIAL,events=[event])
    assert len(rows)==1
    assert 'https://www.sec.gov/8k' in rows[0]['sources']
    assert rows[0]['context']['actual_common_issued']==25e6


def test_financial_retirement_can_supplement_dated_same_financing_from_8k():
    q=('Note 18. Subsequent Events. On July 2, 2026, the Company closed the Private Placement. '
       +REDEEM+' '+LINK)
    event={'accession':'8k','filed':'2026-07-02','sources':['https://www.sec.gov/8k'],
           'combined_text':ISSUE,'terms':{}}
    rows=review(q,events=[event])
    assert rows[0]['context']['assessment']=='RECAPITALIZATION_MIXED'
    assert rows[0]['context']['actual_common_issued']==25e6
    assert 'https://www.sec.gov/8k' in rows[0]['sources']


def test_undated_financing_reference_cannot_join_an_8k_to_old_retirement():
    q='Note 18. Subsequent Events. The Company closed the Private Placement. '+REDEEM+' '+LINK
    event={'accession':'8k','filed':'2026-07-02','sources':['https://www.sec.gov/8k'],
           'combined_text':ISSUE,'terms':{}}
    rows=review(q,events=[event])
    assert rows and rows[0]['context']['link_verification']=='UNKNOWN'
    assert rows[0]['context']['actual_common_issued'] is None


def test_acquisition_completion_date_is_not_a_financing_closing_date():
    q=('Note 18. Subsequent Events. On July 2, 2026, the Company completed the Acquisition '
       'using cash raised in the Private Placement. '+REDEEM+' '+LINK)
    event={'accession':'8k','filed':'2026-07-02','sources':['https://www.sec.gov/8k'],
           'combined_text':ISSUE,'terms':{}}
    rows=review(q,events=[event])
    assert rows[0]['context']['link_verification']=='UNKNOWN'
    assert rows[0]['context']['actual_common_issued'] is None


def test_foreign_cash_is_preserved_and_never_a_usd_claim_reduction():
    cap=review(FINANCIAL.replace('$70 million','C$70 million'))[0]['context']
    assert cap['retirements'][0]['currency']=='CAD'
    assert cap['confirmed_claim_reduction_usd'] is None


def test_unnamed_debt_retirement_stays_visible_and_unverified():
    rows=review('Note 8. Debt. '+ISSUE+' On August 5, 2026, the Company repaid $10 million of debt.')
    assert rows[0]['context']['retirements'][0]['claim_amount']==10e6
    assert rows[0]['context']['retirements'][0]['identity'] is None
    assert rows[0]['context']['link_verification']=='UNKNOWN'


def test_conflicting_same_transaction_currency_cannot_confirm_a_recapitalization():
    event={'accession':'8k','filed':'2026-08-05','sources':['https://www.sec.gov/conflict'],
           'combined_text':ISSUE+' '+REDEEM.replace('$70 million','C$70 million'), 'terms':{}}
    rows=review(FINANCIAL,events=[event])
    assert rows[0]['context']['link_verification']=='UNKNOWN'
    assert rows[0]['context']['source_conflict']
    assert 'https://www.sec.gov/conflict' in rows[0]['sources']


def test_partial_redemption_needs_explicit_remaining_same_class():
    text=FINANCIAL.replace('all outstanding Series D Preferred Stock','36,750 shares of Series D Preferred Stock')
    text+=' Following the Redemption, on August 5, 2026, 18,400 shares of Series D Preferred Stock remained outstanding.'
    cap=review(text)[0]['context']
    assert cap['assessment']=='RECAPITALIZATION_MIXED'
    assert cap['retirements'][0]['whole_instrument'] is False
    assert cap['retirements'][0]['remaining_instrument_units']==18_400


def test_stock_exchange_displays_retired_units_without_inventing_dollar_claim():
    exchange=('On August 5, 2026, the Company exchanged 9,850 shares of Series D Preferred Stock '
              'for 5,500,000 newly issued shares of the Company’s common stock.')
    rows=review('Note 18. Subsequent Events. '+ISSUE+' '+exchange)
    cap=next(r['context'] for r in rows if r['context']['actual_common_issued']==5_500_000)
    assert cap['retirements'][0]['identity']=='series d preferred stock'
    assert cap['retirements'][0]['retired_instrument_units']==9_850
    assert cap['retirements'][0]['claim_amount'] is None
    assert cap['assessment']=='UNKNOWN_USE_OF_PROCEEDS'


def test_nn_br_style_historical_financing_is_separate_from_current_authorization(tmp_path):
    current=('Stockholders approved an increase in authorized common stock from 90 million shares to 180 million shares.')
    class Sec:
        def submissions(self,cik):return {'filings':{'recent':{}}}
        def latest_financial_record(self,cik):return RECORD
        def companyfacts(self,cik):return {}
        def submission_text(self,url):
            if url=='event':return current
            return ('As of August 5, 2026, there were 80,000,000 shares of common stock outstanding. PART I. '
                    +FINANCIAL)
        def relevant_exhibit_texts(self,*a,**kw):return []
    cfg=json.load(open('config/default.json'))
    c=build_candidate(Sec(),{'ticker':'NNBR_CASE','name':'Issuer','cik':'1','exchange':'Nasdaq','security_type':'COMMON_EQUITY'},
                      {'filename':'event','accession':'event','filed':date.today().isoformat(),'form':'8-K','items':'5.03'},
                      {},cfg,{'price':4,'adv20_usd':1e6})
    assert c.event_terms['capital_context']['assessment']=='ISSUANCE_CAPACITY'
    assert c.event_terms['capital_context']['actual_common_issued']==0
    assert c.dilution.common_shares==80e6
    assert c.event_terms['financial_capital_context_history'][0]['context']['actual_common_issued']==25e6
    assert c.gate_status=='DATA_HOLD' and c.dilution.fd_ratio is None
    write_outputs([c],cfg,tmp_path)
    text=(tmp_path/'latest.md').read_text()
    assert 'ISSUANCE_CAPACITY' in text and 'RECAPITALIZATION_MIXED' in text
    assert '25,000,000' in text and '70.0M' in text
    assert json.loads((tmp_path/'quality.json').read_text())['SAFE_TO_ACT'] is False


def test_financial_only_gate_cannot_promote_a_candidate():
    from ssm.gates import evaluate_gates
    c=Candidate('CASE',security_type='COMMON_EQUITY',event_terms={'financial_capital_context_history':[
        {'context':{'assessment':'RECAPITALIZATION_MIXED','reconciliation_required':True}}]},
        dilution=Dilution(common_shares=80e6,confidence='high'))
    assert evaluate_gates(c,json.load(open('config/default.json')))[0]=='DATA_HOLD'


def test_financial_history_is_displayed_separately_from_current_catalysts(tmp_path):
    c=Candidate('CASE',event_type='OTHER',gate_status='DATA_HOLD',
                event_terms={'financial_capital_context_history':review(FINANCIAL)})
    write_outputs([c],json.load(open('config/default.json')),tmp_path)
    text=(tmp_path/'latest.md').read_text()
    assert 'Financial capital history' in text and '25,000,000' in text
    assert 'Material special situations' not in text
